CREATE TABLE `mitemd` (
	`IDDetail` INT NOT NULL AUTO_INCREMENT,
	`IDItem` INT NOT NULL,
	`SatuanBesar` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`Jumlah` FLOAT NULL DEFAULT NULL,
	`Satuan` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`Konversi` FLOAT NULL DEFAULT NULL,
	`HargaJual` DOUBLE NULL DEFAULT '0',
	`LabaPersen` DOUBLE NULL DEFAULT '0',
	PRIMARY KEY (`IDDetail`) USING BTREE,
	INDEX `mitemd_ibfk_1` (`IDItem`) USING BTREE,
	CONSTRAINT `mitemd_ibfk_1` FOREIGN KEY (`IDItem`) REFERENCES `mitem` (`IDItem`) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=40973
;
