CREATE TABLE `tstok` (
	`IDStok` INT NOT NULL AUTO_INCREMENT,
	`IDItem` INT NOT NULL,
	`Kode` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`Tanggal` DATE NOT NULL,
	`Nama` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`Satuan` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`Stok` DOUBLE NULL DEFAULT '0',
	`HargaBeli` DOUBLE NULL DEFAULT '0',
	`HargaJual` DOUBLE NULL DEFAULT '0',
	`Aktif` TINYINT(1) NULL DEFAULT '1',
	PRIMARY KEY (`IDStok`) USING BTREE,
	UNIQUE INDEX `Kode` (`Kode`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=10
;
