CREATE TABLE `tbelihutang` (
	`IDHutang` INT NOT NULL AUTO_INCREMENT,
	`IDSupplier` INT NULL DEFAULT NULL,
	`IDBeliH` INT NULL DEFAULT NULL,
	`NoFaktur` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`Tanggal` DATE NULL DEFAULT NULL,
	`JatuhTempo` DATE NULL DEFAULT NULL,
	`SisaHutang` DECIMAL(18,2) NULL DEFAULT NULL,
	PRIMARY KEY (`IDHutang`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=23
;
