CREATE TABLE `tbelid` (
	`IDBeliD` INT NOT NULL AUTO_INCREMENT,
	`IDBeliH` INT NULL DEFAULT NULL,
	`IDItemD` INT NULL DEFAULT NULL,
	`Qty` DECIMAL(18,2) NULL DEFAULT NULL,
	`Harga` DECIMAL(18,2) NULL DEFAULT NULL,
	`Total` DECIMAL(18,2) NULL DEFAULT NULL,
	`QtyBase` DECIMAL(18,2) NULL DEFAULT NULL,
	PRIMARY KEY (`IDBeliD`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=3
;
