CREATE TABLE `tbelih` (
	`IDBeliH` INT NOT NULL AUTO_INCREMENT,
	`Kode` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`IDSupplier` INT NULL DEFAULT NULL,
	`Tanggal` DATE NULL DEFAULT NULL,
	`JenisBayar` ENUM('Tunai','Kredit') NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`JatuhTempo` DATE NULL DEFAULT NULL,
	`SubTotal` DECIMAL(18,2) NULL DEFAULT NULL,
	`Diskon` DECIMAL(18,2) NULL DEFAULT NULL,
	`Ppn` DECIMAL(18,2) NULL DEFAULT NULL,
	`Total` DECIMAL(18,2) NULL DEFAULT NULL,
	`Status` ENUM('Open','Lunas','Cancel') NULL DEFAULT 'Open' COLLATE 'utf8mb4_0900_ai_ci',
	`InsertUser` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`InsertTime` DATETIME NULL DEFAULT (now()),
	`UpdateUser` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	PRIMARY KEY (`IDBeliH`) USING BTREE,
	UNIQUE INDEX `Kode` (`Kode`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=3
;
